### ISSUE TITLE
HTML is not rendering properly

### ISSUE THREAD

**Issue by Hudda** [shubhamjadon/FlashCards#1]
There is an issue with the cards as if I write HTML in them then HTML tags are printed like strings but I want them to be treated as HTML tags for styling properly. I think it would be better if it is implemented in the app too.

**Comment by shubhamjadon** [comment]
@Hudda Sure i will add the desired feature in the app.

**Comment by shubhamjadon** [comment]
The desired feature have been added to the app hence closing this issue
